### PR TITLE
Merge project quire project

### PR DESCRIPTION
**Pull request by ibilal**
STALLS on npm run build

### CODE REVIEW

**Comment by RickyV33** [comment]
a bunch of tests aren't passing here. Must be from stubs..

**Comment by RickyV33** [comment]
LGTM

**Comment by chances** [comment]
This PR is merging all the SPA integration, too?

**Comment by RickyV33** [comment]
@chances It shouldnt be, I'll have to revert to an earlier commit because all these changes actually got added in.

**Pull request merged**
